import "./globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from 'react-hot-toast'
import {Providers} from "../redux/Provider"
import Navbar from "../components/common/Navbar";
import ClientApplication from "../components/ClientApplication";
import {SocketProvider} from "../context/SocketProvider"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang='en'>
        <SocketProvider>
          <body>
            <Providers>
                <Toaster/>
                <Navbar/>
                <ClientApplication>
                  {children}
                </ClientApplication>
            </Providers>
          </body>
        </SocketProvider>
     </html>
  );
}
