 
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from 'react-hot-toast'
import {Providers} from "../redux/Provider"
const inter = Inter({ subsets: ['latin'] })
import Navbar from '@/components/common/Navbar'

export const metadata: Metadata = {
  title: 'Reshift',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
       <html lang='en'>
       <body>
         <Providers>
             <Navbar/>
             <Toaster/>
             {children}
         </Providers>
       </body>
     </html>
  )
}
